# documentation: https://github.com/crate-ci/typos/blob/master/docs/reference.md

[default.extend-identifiers]
ptd = "ptd"                         # From winwows_sys::Win32::System::Com::FORMATETC { ptd, ..}
requestor = "requestor"             # From x11_dl::xlib::XSelectionEvent { requestor ..}
XF86_Calculater = "XF86_Calculater" # From xkbcommon_dl::keysyms::XF86_Calculater
